version: '3.4'

#Note: remember for connection string just need to set 'redis' for host address
services:
  sepehr.api:
    image: ${DOCKER_REGISTRY-}sepehrapi
    build:
      context: .
      dockerfile: src/Presentation/Sepehr.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
    depends_on:
      - redis
    restart: always
    command: ["--urls", "http://0.0.0.0:80"]
    links:
      - "redis"
  redis:
    container_name: redis
    image: redislabs/redismod
    restart: always
    expose:
      - 6379
    #volumes:
    #  - RedisVolume:/data